- name: PLAY1
  hosts: local # Ansible can manage itself or Ansible can connect self Node
  connection: local # managing its own node, no need of credentials (no need of user-name ,password)
  tasks:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello iam Tagore from PLAY1 and TASK1"

- name: PLAY2
  hosts: local
  connection: local # managing its own node, no need of credentials
  tasks:
  - name: PLAY2 and TASK2
    ansible.builtin.debug:
      msg: "Hello iam Tagore from PLAY2 and TASK2"